name: food_picker
description: "Supabse Practice 001"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.4
  supabase_flutter: ^2.3.4
  image_picker: ^1.0.7
  flutter_naver_map: ^1.2.1
  geolocator: ^11.0.0
  http: ^1.2.1
  daum_postcode_search: ^0.0.2
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0
  flutter_inappwebview: ^5.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/